version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    # volumes:
    #   - ./frontend:/app
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    # command: npm start

  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
